spring:
  application:
    name: planetweb-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/planetcommunity/config-store.git
          search-paths:
            '*service'
server:
  port: 8888
